using System;
using Modelo;
using Oracle.DataAccess.Client;

namespace DAL
{
    public class DALPCORIGEMPRECO
    {
        public DALTABConexao conexao;
        public DALPCORIGEMPRECO (DALTABConexao cx)
        {
            this.conexao = cx;
        }

        public void Incluir(ModeloPCORIGEMPRECO modelo)
        {
            String comando1 = "";
            OracleCommand cmd = new OracleCommand();
            cmd.Connection = conexao.ObjetoConexao;

            comando1 = comando1 + "INSERT INTO PCORIGEMPRECO " + "\n";
            comando1 = comando1 + "     ( " + "\n";
            comando1 = comando1 + "    CODAUTORIZACAO " + "\n";
            comando1 = comando1 + "    ,CODDESCFLEX " + "\n";
            comando1 = comando1 + "    ,CODDESCPBASE " + "\n";
            comando1 = comando1 + "    ,CODDESCPTABELA " + "\n";
            comando1 = comando1 + "    ,CODEMITENTE " + "\n";
            comando1 = comando1 + "    ,CODFIGVENDATRIANGULAR " + "\n";
            comando1 = comando1 + "    ,CODFILIAL " + "\n";
            comando1 = comando1 + "    ,CODFILIALNF " + "\n";
            comando1 = comando1 + "    ,CODFISCAL " + "\n";
            comando1 = comando1 + "    ,CODPRECOFIXO " + "\n";
            comando1 = comando1 + "    ,CODPROD " + "\n";
            comando1 = comando1 + "    ,CODROTINADESCFLEX " + "\n";
            comando1 = comando1 + "    ,CODROTINADESCPTABELA " + "\n";
            comando1 = comando1 + "    ,CODROTINAPBASE " + "\n";
            comando1 = comando1 + "    ,COLUNAPRECO " + "\n";
            comando1 = comando1 + "    ,CREDITAPOLITICAPBASE " + "\n";
            comando1 = comando1 + "    ,DATA " + "\n";
            comando1 = comando1 + "    ,DTFIMAUTOR " + "\n";
            comando1 = comando1 + "    ,DTFIMDESCFLEX " + "\n";
            comando1 = comando1 + "    ,DTFIMDESCPBASE " + "\n";
            comando1 = comando1 + "    ,DTFIMDESCPTABELA " + "\n";
            comando1 = comando1 + "    ,DTFIMDESCVOLUME " + "\n";
            comando1 = comando1 + "    ,DTFIMOFERTA " + "\n";
            comando1 = comando1 + "    ,DTINICIOAUTOR " + "\n";
            comando1 = comando1 + "    ,DTINICIODESCFLEX " + "\n";
            comando1 = comando1 + "    ,DTINICIODESCPBASE " + "\n";
            comando1 = comando1 + "    ,DTINICIODESCPTABELA " + "\n";
            comando1 = comando1 + "    ,DTINICIODESCVOLUME " + "\n";
            comando1 = comando1 + "    ,DTINICIOOFERTA " + "\n";
            comando1 = comando1 + "    ,FATORPRECO " + "\n";
            comando1 = comando1 + "    ,FIMINTERVALO " + "\n";
            comando1 = comando1 + "    ,FIMINTERVALOAUTORI " + "\n";
            comando1 = comando1 + "    ,FIMINTERVALOPBASE " + "\n";
            comando1 = comando1 + "    ,FIMINTERVALOPTABELA " + "\n";
            comando1 = comando1 + "    ,INICIOINTERVALO " + "\n";
            comando1 = comando1 + "    ,INICIOINTERVALOAUTORI " + "\n";
            comando1 = comando1 + "    ,INICIOINTERVALOPBASE " + "\n";
            comando1 = comando1 + "    ,INICIOINTERVALOPTABELA " + "\n";
            comando1 = comando1 + "    ,NAODEBITAPOLITICAPBASE " + "\n";
            comando1 = comando1 + "    ,NUMPED " + "\n";
            comando1 = comando1 + "    ,NUMREGIAO " + "\n";
            comando1 = comando1 + "    ,NUMSEQ " + "\n";
            comando1 = comando1 + "    ,ORIGEMPED " + "\n";
            comando1 = comando1 + "    ,ORIGEMPEDFLEX " + "\n";
            comando1 = comando1 + "    ,ORIGEMPEDPBASE " + "\n";
            comando1 = comando1 + "    ,ORIGEMPEDPTABELA " + "\n";
            comando1 = comando1 + "    ,ORIGEMPRECO " + "\n";
            comando1 = comando1 + "    ,PERACRESCISMOSIMPNAC " + "\n";
            comando1 = comando1 + "    ,PERBONIFIC " + "\n";
            comando1 = comando1 + "    ,PERCACRESCBALCAO " + "\n";
            comando1 = comando1 + "    ,PERCACRESCIMOTELEMARKETING " + "\n";
            comando1 = comando1 + "    ,PERCACRESCPF " + "\n";
            comando1 = comando1 + "    ,PERCDESCABATIMENTO " + "\n";
            comando1 = comando1 + "    ,PERCDESCAUTOR " + "\n";
            comando1 = comando1 + "    ,PERCDESCCOFINS " + "\n";
            comando1 = comando1 + "    ,PERCDESCFLEX " + "\n";
            comando1 = comando1 + "    ,PERCDESCPBASE " + "\n";
            comando1 = comando1 + "    ,PERCDESCPIS " + "\n";
            comando1 = comando1 + "    ,PERCDESCPTABELA " + "\n";
            comando1 = comando1 + "    ,PERCDESCVOLUME " + "\n";
            comando1 = comando1 + "    ,PERCFRETE " + "\n";
            comando1 = comando1 + "    ,PERCPLPAG " + "\n";
            comando1 = comando1 + "    ,PERCRAMOATIV " + "\n";
            comando1 = comando1 + "    ,PERCREDALIQIPI " + "\n";
            comando1 = comando1 + "    ,PERDESCCOM " + "\n";
            comando1 = comando1 + "    ,PORIGINAL " + "\n";
            comando1 = comando1 + "    ,QTMINATACADO " + "\n";
            comando1 = comando1 + "    ,SITTRIBUT " + "\n";
            comando1 = comando1 + "    ,TIPOBROKER " + "\n";
            comando1 = comando1 + "    ,TIPODESCFLEX " + "\n";
            comando1 = comando1 + "    ,TIPODESCPBASE " + "\n";
            comando1 = comando1 + "    ,TIPODESCPTABELA " + "\n";
            comando1 = comando1 + "    ,TIPOFRETE " + "\n";
            comando1 = comando1 + "    ,USATRIBUTPORUF " + "\n";
            comando1 = comando1 + "    ,VLBONIFIC " + "\n";
            comando1 = comando1 + "    ,VLDESCABATIMENTO " + "\n";
            comando1 = comando1 + "    ,VLDESCCOM " + "\n";
            comando1 = comando1 + "    ,VLDESCICMS " + "\n";
            comando1 = comando1 + "    ,VLDESCREDUCAOCOFINS " + "\n";
            comando1 = comando1 + "    ,VLDESCREDUCAOPIS " + "\n";
            comando1 = comando1 + "    ,VLDIFALIQUOTAS " + "\n";
            comando1 = comando1 + "    ,VLICMSDIFALIQPART " + "\n";
            comando1 = comando1 + "    ,VLICMSPARTILHA " + "\n";
            comando1 = comando1 + "    ,VLIPI " + "\n";
            comando1 = comando1 + "    ,VLREDPVENDASIMPLESNA " + "\n";
            comando1 = comando1 + "    ,VLREPASSE " + "\n";
            comando1 = comando1 + "    ,VLST " + "\n";
            comando1 = comando1 + "    ,VLSUFRAMA " + "\n";
            comando1 = comando1 + "    ) " + "\n";
            comando1 = comando1 + "    VALUES " + "\n";
            comando1 = comando1 + "    ( " + "\n";
            comando1 = comando1 + "    :CODAUTORIZACAO " + "\n";
            comando1 = comando1 + "    ,:CODDESCFLEX " + "\n";
            comando1 = comando1 + "    ,:CODDESCPBASE " + "\n";
            comando1 = comando1 + "    ,:CODDESCPTABELA " + "\n";
            comando1 = comando1 + "    ,:CODEMITENTE " + "\n";
            comando1 = comando1 + "    ,:CODFIGVENDATRIANGULAR " + "\n";
            comando1 = comando1 + "    ,:CODFILIAL " + "\n";
            comando1 = comando1 + "    ,:CODFILIALNF " + "\n";
            comando1 = comando1 + "    ,:CODFISCAL " + "\n";
            comando1 = comando1 + "    ,:CODPRECOFIXO " + "\n";
            comando1 = comando1 + "    ,:CODPROD " + "\n";
            comando1 = comando1 + "    ,:CODROTINADESCFLEX " + "\n";
            comando1 = comando1 + "    ,:CODROTINADESCPTABELA " + "\n";
            comando1 = comando1 + "    ,:CODROTINAPBASE " + "\n";
            comando1 = comando1 + "    ,:COLUNAPRECO " + "\n";
            comando1 = comando1 + "    ,:CREDITAPOLITICAPBASE " + "\n";
            comando1 = comando1 + "    ,:DATA " + "\n";
            comando1 = comando1 + "    ,:DTFIMAUTOR " + "\n";
            comando1 = comando1 + "    ,:DTFIMDESCFLEX " + "\n";
            comando1 = comando1 + "    ,:DTFIMDESCPBASE " + "\n";
            comando1 = comando1 + "    ,:DTFIMDESCPTABELA " + "\n";
            comando1 = comando1 + "    ,:DTFIMDESCVOLUME " + "\n";
            comando1 = comando1 + "    ,:DTFIMOFERTA " + "\n";
            comando1 = comando1 + "    ,:DTINICIOAUTOR " + "\n";
            comando1 = comando1 + "    ,:DTINICIODESCFLEX " + "\n";
            comando1 = comando1 + "    ,:DTINICIODESCPBASE " + "\n";
            comando1 = comando1 + "    ,:DTINICIODESCPTABELA " + "\n";
            comando1 = comando1 + "    ,:DTINICIODESCVOLUME " + "\n";
            comando1 = comando1 + "    ,:DTINICIOOFERTA " + "\n";
            comando1 = comando1 + "    ,:FATORPRECO " + "\n";
            comando1 = comando1 + "    ,:FIMINTERVALO " + "\n";
            comando1 = comando1 + "    ,:FIMINTERVALOAUTORI " + "\n";
            comando1 = comando1 + "    ,:FIMINTERVALOPBASE " + "\n";
            comando1 = comando1 + "    ,:FIMINTERVALOPTABELA " + "\n";
            comando1 = comando1 + "    ,:INICIOINTERVALO " + "\n";
            comando1 = comando1 + "    ,:INICIOINTERVALOAUTORI " + "\n";
            comando1 = comando1 + "    ,:INICIOINTERVALOPBASE " + "\n";
            comando1 = comando1 + "    ,:INICIOINTERVALOPTABELA " + "\n";
            comando1 = comando1 + "    ,:NAODEBITAPOLITICAPBASE " + "\n";
            comando1 = comando1 + "    ,:NUMPED " + "\n";
            comando1 = comando1 + "    ,:NUMREGIAO " + "\n";
            comando1 = comando1 + "    ,:NUMSEQ " + "\n";
            comando1 = comando1 + "    ,:ORIGEMPED " + "\n";
            comando1 = comando1 + "    ,:ORIGEMPEDFLEX " + "\n";
            comando1 = comando1 + "    ,:ORIGEMPEDPBASE " + "\n";
            comando1 = comando1 + "    ,:ORIGEMPEDPTABELA " + "\n";
            comando1 = comando1 + "    ,:ORIGEMPRECO " + "\n";
            comando1 = comando1 + "    ,:PERACRESCISMOSIMPNAC " + "\n";
            comando1 = comando1 + "    ,:PERBONIFIC " + "\n";
            comando1 = comando1 + "    ,:PERCACRESCBALCAO " + "\n";
            comando1 = comando1 + "    ,:PERCACRESCIMOTELEMARKETING " + "\n";
            comando1 = comando1 + "    ,:PERCACRESCPF " + "\n";
            comando1 = comando1 + "    ,:PERCDESCABATIMENTO " + "\n";
            comando1 = comando1 + "    ,:PERCDESCAUTOR " + "\n";
            comando1 = comando1 + "    ,:PERCDESCCOFINS " + "\n";
            comando1 = comando1 + "    ,:PERCDESCFLEX " + "\n";
            comando1 = comando1 + "    ,:PERCDESCPBASE " + "\n";
            comando1 = comando1 + "    ,:PERCDESCPIS " + "\n";
            comando1 = comando1 + "    ,:PERCDESCPTABELA " + "\n";
            comando1 = comando1 + "    ,:PERCDESCVOLUME " + "\n";
            comando1 = comando1 + "    ,:PERCFRETE " + "\n";
            comando1 = comando1 + "    ,:PERCPLPAG " + "\n";
            comando1 = comando1 + "    ,:PERCRAMOATIV " + "\n";
            comando1 = comando1 + "    ,:PERCREDALIQIPI " + "\n";
            comando1 = comando1 + "    ,:PERDESCCOM " + "\n";
            comando1 = comando1 + "    ,:PORIGINAL " + "\n";
            comando1 = comando1 + "    ,:QTMINATACADO " + "\n";
            comando1 = comando1 + "    ,:SITTRIBUT " + "\n";
            comando1 = comando1 + "    ,:TIPOBROKER " + "\n";
            comando1 = comando1 + "    ,:TIPODESCFLEX " + "\n";
            comando1 = comando1 + "    ,:TIPODESCPBASE " + "\n";
            comando1 = comando1 + "    ,:TIPODESCPTABELA " + "\n";
            comando1 = comando1 + "    ,:TIPOFRETE " + "\n";
            comando1 = comando1 + "    ,:USATRIBUTPORUF " + "\n";
            comando1 = comando1 + "    ,:VLBONIFIC " + "\n";
            comando1 = comando1 + "    ,:VLDESCABATIMENTO " + "\n";
            comando1 = comando1 + "    ,:VLDESCCOM " + "\n";
            comando1 = comando1 + "    ,:VLDESCICMS " + "\n";
            comando1 = comando1 + "    ,:VLDESCREDUCAOCOFINS " + "\n";
            comando1 = comando1 + "    ,:VLDESCREDUCAOPIS " + "\n";
            comando1 = comando1 + "    ,:VLDIFALIQUOTAS " + "\n";
            comando1 = comando1 + "    ,:VLICMSDIFALIQPART " + "\n";
            comando1 = comando1 + "    ,:VLICMSPARTILHA " + "\n";
            comando1 = comando1 + "    ,:VLIPI " + "\n";
            comando1 = comando1 + "    ,:VLREDPVENDASIMPLESNA " + "\n";
            comando1 = comando1 + "    ,:VLREPASSE " + "\n";
            comando1 = comando1 + "    ,:VLST " + "\n";
            comando1 = comando1 + "    ,:VLSUFRAMA)";
            cmd.CommandText = comando1;
            cmd.Parameters.Add(new OracleParameter(":CODAUTORIZACAO", modelo.codautorizacao));
            cmd.Parameters.Add(new OracleParameter(":CODDESCFLEX", modelo.coddescflex));
            cmd.Parameters.Add(new OracleParameter(":CODDESCPBASE", modelo.coddescpbase));
            cmd.Parameters.Add(new OracleParameter(":CODDESCPTABELA", modelo.coddescptabela));
            cmd.Parameters.Add(new OracleParameter(":CODEMITENTE", modelo.codemitente));
            cmd.Parameters.Add(new OracleParameter(":CODFIGVENDATRIANGULAR", modelo.codfigvendatriangular));
            cmd.Parameters.Add(new OracleParameter(":CODFILIAL", modelo.codfilial));
            cmd.Parameters.Add(new OracleParameter(":CODFILIALNF", modelo.codfilialnf));
            cmd.Parameters.Add(new OracleParameter(":CODFISCAL", modelo.codfiscal));
            cmd.Parameters.Add(new OracleParameter(":CODPRECOFIXO", modelo.codprecofixo));
            cmd.Parameters.Add(new OracleParameter(":CODPROD", modelo.codprod));
            cmd.Parameters.Add(new OracleParameter(":CODROTINADESCFLEX", modelo.codrotinadescflex));
            cmd.Parameters.Add(new OracleParameter(":CODROTINADESCPTABELA", modelo.codrotinadescptabela));
            cmd.Parameters.Add(new OracleParameter(":CODROTINAPBASE", modelo.codrotinapbase));
            cmd.Parameters.Add(new OracleParameter(":COLUNAPRECO", modelo.colunapreco));
            cmd.Parameters.Add(new OracleParameter(":CREDITAPOLITICAPBASE", modelo.creditapoliticapbase));
            cmd.Parameters.Add(new OracleParameter(":DATA", modelo.data));
            cmd.Parameters.Add(new OracleParameter(":DTFIMAUTOR", modelo.dtfimautor));
            cmd.Parameters.Add(new OracleParameter(":DTFIMDESCFLEX", modelo.dtfimdescflex));
            cmd.Parameters.Add(new OracleParameter(":DTFIMDESCPBASE", modelo.dtfimdescpbase));
            cmd.Parameters.Add(new OracleParameter(":DTFIMDESCPTABELA", modelo.dtfimdescptabela));
            cmd.Parameters.Add(new OracleParameter(":DTFIMDESCVOLUME", modelo.dtfimdescvolume));
            cmd.Parameters.Add(new OracleParameter(":DTFIMOFERTA", modelo.dtfimoferta));
            cmd.Parameters.Add(new OracleParameter(":DTINICIOAUTOR", modelo.dtinicioautor));
            cmd.Parameters.Add(new OracleParameter(":DTINICIODESCFLEX", modelo.dtiniciodescflex));
            cmd.Parameters.Add(new OracleParameter(":DTINICIODESCPBASE", modelo.dtiniciodescpbase));
            cmd.Parameters.Add(new OracleParameter(":DTINICIODESCPTABELA", modelo.dtiniciodescptabela));
            cmd.Parameters.Add(new OracleParameter(":DTINICIODESCVOLUME", modelo.dtiniciodescvolume));
            cmd.Parameters.Add(new OracleParameter(":DTINICIOOFERTA", modelo.dtiniciooferta));
            cmd.Parameters.Add(new OracleParameter(":FATORPRECO", modelo.fatorpreco));
            cmd.Parameters.Add(new OracleParameter(":FIMINTERVALO", modelo.fimintervalo));
            cmd.Parameters.Add(new OracleParameter(":FIMINTERVALOAUTORI", modelo.fimintervaloautori));
            cmd.Parameters.Add(new OracleParameter(":FIMINTERVALOPBASE", modelo.fimintervalopbase));
            cmd.Parameters.Add(new OracleParameter(":FIMINTERVALOPTABELA", modelo.fimintervaloptabela));
            cmd.Parameters.Add(new OracleParameter(":INICIOINTERVALO", modelo.iniciointervalo));
            cmd.Parameters.Add(new OracleParameter(":INICIOINTERVALOAUTORI", modelo.iniciointervaloautori));
            cmd.Parameters.Add(new OracleParameter(":INICIOINTERVALOPBASE", modelo.iniciointervalopbase));
            cmd.Parameters.Add(new OracleParameter(":INICIOINTERVALOPTABELA", modelo.iniciointervaloptabela));
            cmd.Parameters.Add(new OracleParameter(":NAODEBITAPOLITICAPBASE", modelo.naodebitapoliticapbase));
            cmd.Parameters.Add(new OracleParameter(":NUMPED", modelo.numped));
            cmd.Parameters.Add(new OracleParameter(":NUMREGIAO", modelo.numregiao));
            cmd.Parameters.Add(new OracleParameter(":NUMSEQ", modelo.numseq));
            cmd.Parameters.Add(new OracleParameter(":ORIGEMPED", modelo.origemped));
            cmd.Parameters.Add(new OracleParameter(":ORIGEMPEDFLEX", modelo.origempedflex));
            cmd.Parameters.Add(new OracleParameter(":ORIGEMPEDPBASE", modelo.origempedpbase));
            cmd.Parameters.Add(new OracleParameter(":ORIGEMPEDPTABELA", modelo.origempedptabela));
            cmd.Parameters.Add(new OracleParameter(":ORIGEMPRECO", modelo.origempreco));
            cmd.Parameters.Add(new OracleParameter(":PERACRESCISMOSIMPNAC", modelo.peracrescismosimpnac));
            cmd.Parameters.Add(new OracleParameter(":PERBONIFIC", modelo.perbonific));
            cmd.Parameters.Add(new OracleParameter(":PERCACRESCBALCAO", modelo.percacrescbalcao));
            cmd.Parameters.Add(new OracleParameter(":PERCACRESCIMOTELEMARKETING", modelo.percacrescimotelemarketing));
            cmd.Parameters.Add(new OracleParameter(":PERCACRESCPF", modelo.percacrescpf));
            cmd.Parameters.Add(new OracleParameter(":PERCDESCABATIMENTO", modelo.percdescabatimento));
            cmd.Parameters.Add(new OracleParameter(":PERCDESCAUTOR", modelo.percdescautor));
            cmd.Parameters.Add(new OracleParameter(":PERCDESCCOFINS", modelo.percdesccofins));
            cmd.Parameters.Add(new OracleParameter(":PERCDESCFLEX", modelo.percdescflex));
            cmd.Parameters.Add(new OracleParameter(":PERCDESCPBASE", modelo.percdescpbase));
            cmd.Parameters.Add(new OracleParameter(":PERCDESCPIS", modelo.percdescpis));
            cmd.Parameters.Add(new OracleParameter(":PERCDESCPTABELA", modelo.percdescptabela));
            cmd.Parameters.Add(new OracleParameter(":PERCDESCVOLUME", modelo.percdescvolume));
            cmd.Parameters.Add(new OracleParameter(":PERCFRETE", modelo.percfrete));
            cmd.Parameters.Add(new OracleParameter(":PERCPLPAG", modelo.percplpag));
            cmd.Parameters.Add(new OracleParameter(":PERCRAMOATIV", modelo.percramoativ));
            cmd.Parameters.Add(new OracleParameter(":PERCREDALIQIPI", modelo.percredaliqipi));
            cmd.Parameters.Add(new OracleParameter(":PERDESCCOM", modelo.perdesccom));
            cmd.Parameters.Add(new OracleParameter(":PORIGINAL", modelo.poriginal));
            cmd.Parameters.Add(new OracleParameter(":QTMINATACADO", modelo.qtminatacado));
            cmd.Parameters.Add(new OracleParameter(":SITTRIBUT", modelo.sittribut));
            cmd.Parameters.Add(new OracleParameter(":TIPOBROKER", modelo.tipobroker));
            cmd.Parameters.Add(new OracleParameter(":TIPODESCFLEX", modelo.tipodescflex));
            cmd.Parameters.Add(new OracleParameter(":TIPODESCPBASE", modelo.tipodescpbase));
            cmd.Parameters.Add(new OracleParameter(":TIPODESCPTABELA", modelo.tipodescptabela));
            cmd.Parameters.Add(new OracleParameter(":TIPOFRETE", modelo.tipofrete));
            cmd.Parameters.Add(new OracleParameter(":USATRIBUTPORUF", modelo.usatributporuf));
            cmd.Parameters.Add(new OracleParameter(":VLBONIFIC", modelo.vlbonific));
            cmd.Parameters.Add(new OracleParameter(":VLDESCABATIMENTO", modelo.vldescabatimento));
            cmd.Parameters.Add(new OracleParameter(":VLDESCCOM", modelo.vldesccom));
            cmd.Parameters.Add(new OracleParameter(":VLDESCICMS", modelo.vldescicms));
            cmd.Parameters.Add(new OracleParameter(":VLDESCREDUCAOCOFINS", modelo.vldescreducaocofins));
            cmd.Parameters.Add(new OracleParameter(":VLDESCREDUCAOPIS", modelo.vldescreducaopis));
            cmd.Parameters.Add(new OracleParameter(":VLDIFALIQUOTAS", modelo.vldifaliquotas));
            cmd.Parameters.Add(new OracleParameter(":VLICMSDIFALIQPART", modelo.vlicmsdifaliqpart));
            cmd.Parameters.Add(new OracleParameter(":VLICMSPARTILHA", modelo.vlicmspartilha));
            cmd.Parameters.Add(new OracleParameter(":VLIPI", modelo.vlipi));
            cmd.Parameters.Add(new OracleParameter(":VLREDPVENDASIMPLESNA", modelo.vlredpvendasimplesna));
            cmd.Parameters.Add(new OracleParameter(":VLREPASSE", modelo.vlrepasse));
            cmd.Parameters.Add(new OracleParameter(":VLST", modelo.vlst));
            cmd.Parameters.Add(new OracleParameter(":VLSUFRAMA", modelo.vlsuframa));
            conexao.Conectar();
            cmd.ExecuteNonQuery();
            conexao.Desconectar();
        }
    }
}
